In [3]:
import pandas as pd

# Match results
results = pd.read_csv('../data/raw/results.csv')

# FIFA rankings
fifa_rankings = pd.read_csv('../data/raw/fifa_rankings.csv')

# Transfermarkt files
players = pd.read_csv('../data/raw/transfermarkt/players.csv')
player_valuations = pd.read_csv('../data/raw/transfermarkt/player_valuations.csv')
national_teams = pd.read_csv('../data/raw/transfermarkt/national_teams.csv')
games = pd.read_csv('../data/raw/transfermarkt/games.csv')
game_lineups = pd.read_csv('../data/raw/transfermarkt/game_lineups.csv', low_memory=False)

In [4]:
game_lineups['number'].unique()

<StringArray>
[  '5',   '4',  '11',  '17',  '23',  '29',   '1',  '20',  '12',  '16',
 ...
 '195', '232', '218', '136', '241', '142', '256', '170', '139', '206']
Length: 169, dtype: str

In [5]:
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [7]:
results.shape

(49411, 9)

In [8]:
results.info

<bound method DataFrame.info of              date home_team   away_team  home_score  away_score  \
0      1872-11-30  Scotland     England         0.0         0.0
1      1873-03-08   England    Scotland         4.0         2.0
2      1874-03-07  Scotland     England         2.0         1.0
3      1875-03-06   England    Scotland         2.0         2.0
4      1876-03-04  Scotland     England         3.0         0.0
...           ...       ...         ...         ...         ...
49406  2026-06-27    Jordan   Argentina         NaN         NaN
49407  2026-06-27  Colombia    Portugal         NaN         NaN
49408  2026-06-27  DR Congo  Uzbekistan         NaN         NaN
49409  2026-06-27    Panama     England         NaN         NaN
49410  2026-06-27   Croatia       Ghana         NaN         NaN

           tournament             city        country  neutral
0            Friendly          Glasgow       Scotland    False
1            Friendly           London        England    False
2            Friendly          Glasgow       Scotland    False
3            Friendly           London        England    False
4            Friendly          Glasgow       Scotland    False
...               ...              ...            ...      ...
49406  FIFA World Cup        Arlington  United States     True
49407  FIFA World Cup    Miami Gardens  United States     True
49408  FIFA World Cup          Atlanta  United States     True
49409  FIFA World Cup  East Rutherford  United States     True
49410  FIFA World Cup     Philadelphia  United States     True

[49411 rows x 9 columns]>

In [9]:
results.isnull().sum()

date           0
home_team      0
away_team      0
home_score    72
away_score    72
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [10]:
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 49411 entries, 0 to 49410
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49411 non-null  str
 1   home_team   49411 non-null  str
 2   away_team   49411 non-null  str
 3   home_score  49339 non-null  float64
 4   away_score  49339 non-null  float64
 5   tournament  49411 non-null  str
 6   city        49411 non-null  str
 7   country     49411 non-null  str
 8   neutral     49411 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB

In [11]:
fifa_rankings.head()

,Unnamed: 0,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31

In [12]:
fifa_rankings.shape

(70194, 9)

In [13]:
fifa_rankings.info()

<class 'pandas.DataFrame'>
RangeIndex: 70194 entries, 0 to 70193
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       70194 non-null  int64
 1   rank             70185 non-null  float64
 2   country_full     70194 non-null  str
 3   country_abrv     70194 non-null  str
 4   total_points     70194 non-null  float64
 5   previous_points  70194 non-null  float64
 6   rank_change      70194 non-null  int64
 7   confederation    70194 non-null  str
 8   rank_date        70194 non-null  str
dtypes: float64(3), int64(2), str(4)
memory usage: 4.8 MB

In [14]:
fifa_rankings.isnull().sum()

Unnamed: 0         0
rank               9
country_full       0
country_abrv       0
total_points       0
previous_points    0
rank_change        0
confederation      0
rank_date          0
dtype: int64

In [15]:
fifa_rankings[fifa_rankings['rank'].isnull()]

,Unnamed: 0,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
66339,66339,NaN,Eritrea,ERI,855.56,0.0,0,CAF,2023-10-26
66340,66340,NaN,Tonga,TGA,861.81,0.0,0,OFC,2023-10-26
66341,66341,NaN,Samoa,SAM,894.26,0.0,0,OFC,2023-10-26
66342,66342,NaN,American Samoa,ASA,900.27,0.0,0,OFC,2023-10-26
66493,66493,NaN,Eritrea,ERI,855.56,0.0,0,CAF,2023-11-30
66734,66734,NaN,Eritrea,ERI,855.56,0.0,0,CAF,2023-12-21
66919,66919,NaN,Eritrea,ERI,855.56,0.0,0,CAF,2024-02-15
67134,67134,NaN,Eritrea,ERI,855.56,0.0,0,CAF,2024-04-04
67393,67393,NaN,Eritrea,ERI,855.56,0.0,0,CAF,2024-06-20

In [17]:
players.head()
players.shape
players.info()
players.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 47701 entries, 0 to 47700
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             47701 non-null  int64
 1   first_name                            44610 non-null  str
 2   last_name                             47701 non-null  str
 3   name                                  47701 non-null  str
 4   last_season                           47701 non-null  int64
 5   current_club_id                       47701 non-null  int64
 6   player_code                           47701 non-null  str
 7   country_of_birth                      42535 non-null  str
 8   city_of_birth                         42811 non-null  str
 9   country_of_citizenship                47428 non-null  str
 10  date_of_birth                         47652 non-null  str
 11  sub_position                          47240 non-null  str
 12  position                              47701 non-null  str
 13  foot                                  42604 non-null  str
 14  height_in_cm                          44044 non-null  float64
 15  contract_expiration_date              31328 non-null  str
 16  agent_name                            25656 non-null  str
 17  image_url                             47701 non-null  str
 18  international_caps                    17594 non-null  float64
 19  international_goals                   17594 non-null  float64
 20  current_national_team_id              2454 non-null   float64
 21  url                                   47701 non-null  str
 22  current_club_domestic_competition_id  45432 non-null  str
 23  current_club_name                     45432 non-null  str
 24  market_value_in_eur                   31507 non-null  float64
 25  highest_market_value_in_eur           31507 non-null  float64
dtypes: float64(6), int64(3), str(17)
memory usage: 9.5 MB

player_id                                   0
first_name                               3091
last_name                                   0
name                                        0
last_season                                 0
current_club_id                             0
player_code                                 0
country_of_birth                         5166
city_of_birth                            4890
country_of_citizenship                    273
date_of_birth                              49
sub_position                              461
position                                    0
foot                                     5097
height_in_cm                             3657
contract_expiration_date                16373
agent_name                              22045
image_url                                   0
international_caps                      30107
international_goals                     30107
current_national_team_id                45247
url                                         0
current_club_domestic_competition_id     2269
current_club_name                        2269
market_value_in_eur                     16194
highest_market_value_in_eur             16194
dtype: int64

In [18]:
players.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [19]:
players.shape

(47701, 26)

In [20]:
players.info()

<class 'pandas.DataFrame'>
RangeIndex: 47701 entries, 0 to 47700
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             47701 non-null  int64
 1   first_name                            44610 non-null  str
 2   last_name                             47701 non-null  str
 3   name                                  47701 non-null  str
 4   last_season                           47701 non-null  int64
 5   current_club_id                       47701 non-null  int64
 6   player_code                           47701 non-null  str
 7   country_of_birth                      42535 non-null  str
 8   city_of_birth                         42811 non-null  str
 9   country_of_citizenship                47428 non-null  str
 10  date_of_birth                         47652 non-null  str
 11  sub_position                          47240 non-null  str
 12  position                              47701 non-null  str
 13  foot                                  42604 non-null  str
 14  height_in_cm                          44044 non-null  float64
 15  contract_expiration_date              31328 non-null  str
 16  agent_name                            25656 non-null  str
 17  image_url                             47701 non-null  str
 18  international_caps                    17594 non-null  float64
 19  international_goals                   17594 non-null  float64
 20  current_national_team_id              2454 non-null   float64
 21  url                                   47701 non-null  str
 22  current_club_domestic_competition_id  45432 non-null  str
 23  current_club_name                     45432 non-null  str
 24  market_value_in_eur                   31507 non-null  float64
 25  highest_market_value_in_eur           31507 non-null  float64
dtypes: float64(6), int64(3), str(17)
memory usage: 9.5 MB

In [21]:
players.isnull().sum

<bound method DataFrame.sum of        player_id  first_name  last_name   name  last_season  current_club_id  \
0          False       False      False  False        False            False
1          False       False      False  False        False            False
2          False       False      False  False        False            False
3          False        True      False  False        False            False
4          False       False      False  False        False            False
...          ...         ...        ...    ...          ...              ...
47696      False       False      False  False        False            False
47697      False       False      False  False        False            False
47698      False       False      False  False        False            False
47699      False       False      False  False        False            False
47700      False       False      False  False        False            False

       player_code  country_of_birth  city_of_birth  country_of_citizenship  \
0            False             False          False                   False
1            False             False          False                   False
2            False             False          False                   False
3            False             False          False                   False
4            False             False          False                   False
...            ...               ...            ...                     ...
47696        False              True           True                   False
47697        False              True           True                   False
47698        False              True           True                   False
47699        False              True           True                   False
47700        False              True           True                   False

       ...  agent_name  image_url  international_caps  international_goals  \
0      ...       False      False                True                 True
1      ...       False      False                True                 True
2      ...       False      False                True                 True
3      ...        True      False                True                 True
4      ...       False      False                True                 True
...    ...         ...        ...                 ...                  ...
47696  ...        True      False                True                 True
47697  ...        True      False                True                 True
47698  ...       False      False                True                 True
47699  ...        True      False                True                 True
47700  ...        True      False                True                 True

       current_national_team_id    url  current_club_domestic_competition_id  \
0                          True  False                                 False
1                          True  False                                 False
2                          True  False                                 False
3                          True  False                                 False
4                          True  False                                 False
...                         ...    ...                                   ...
47696                      True  False                                 False
47697                      True  False                                 False
47698                      True  False                                 False
47699                      True  False                                 False
47700                      True  False                                 False

       current_club_name  market_value_in_eur  highest_market_value_in_eur
0                  False                False                        False
1                  False                False                        False
2                  False                False                        False
3                  False                False                        False
4                  False                False                        False
...                  ...                  ...                          ...
47696              False                 True                         True
47697              False                 True                         True
47698              False                 True                         True
47699              False                 True                         True
47700              False                 True                         True

[47701 rows x 26 columns]>

In [22]:
player_valuations.head()

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057,BE1
1,342216,2001-07-20,100000,Unknown,1241,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126,TR1
3,6893,2003-12-15,900000,Galatasaray,984,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398,IT1

In [23]:
player_valuations.shape

(507815, 6)

In [24]:
player_valuations.info()

<class 'pandas.DataFrame'>
RangeIndex: 507815 entries, 0 to 507814
Data columns (total 6 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   player_id                            507815 non-null  int64
 1   date                                 507815 non-null  str
 2   market_value_in_eur                  507815 non-null  int64
 3   current_club_name                    507815 non-null  str
 4   current_club_id                      507815 non-null  int64
 5   player_club_domestic_competition_id  485216 non-null  str
dtypes: int64(3), str(3)
memory usage: 23.2 MB

In [25]:
player_valuations.isnull().sum()

player_id                                  0
date                                       0
market_value_in_eur                        0
current_club_name                          0
current_club_id                            0
player_club_domestic_competition_id    22599
dtype: int64

In [26]:
national_teams.head()

,national_team_id,name,team_code,country_id,country_name,country_code,confederation,team_image_url,squad_size,average_age,foreigners_number,foreigners_percentage,total_market_value,coach_name,fifa_ranking,last_season,url
0,10521,San Marino,san-marino,144,San Marino,SMR1,UEFA,https://tmssl.akamaized.net//images/flagge/hea...,24,24.9,17,70.8,995000.0,NaN,211,2025,https://www.transfermarkt.co.uk/san-marino/sta...
1,10533,Andorra,andorra,5,Andorra,AND2,UEFA,https://tmssl.akamaized.net//images/flagge/hea...,26,29.2,11,42.3,3380000.0,NaN,173,2025,https://www.transfermarkt.co.uk/andorra/starts...
2,11953,Montenegro,montenegro,216,Montenegro,MNE1,UEFA,https://tmssl.akamaized.net//images/flagge/hea...,26,28.3,24,92.3,60130001.0,NaN,81,2025,https://www.transfermarkt.co.uk/montenegro/sta...
3,13342,Guatemala,guatemala,58,Guatemala,GU1A,CONCACAF,https://tmssl.akamaized.net//images/flagge/hea...,21,25.2,6,28.6,5330000.0,NaN,96,2025,https://www.transfermarkt.co.uk/guatemala/star...
4,13497,Uganda,uganda,176,Uganda,UGL1,CAF,https://tmssl.akamaized.net//images/flagge/hea...,28,28.0,23,82.1,8700000.0,NaN,88,2025,https://www.transfermarkt.co.uk/uganda/startse...

In [28]:
national_teams.shape

(118, 17)

In [29]:
national_teams.info()

<class 'pandas.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   national_team_id       118 non-null    int64
 1   name                   118 non-null    str
 2   team_code              118 non-null    str
 3   country_id             118 non-null    int64
 4   country_name           118 non-null    str
 5   country_code           118 non-null    str
 6   confederation          117 non-null    str
 7   team_image_url         118 non-null    str
 8   squad_size             118 non-null    int64
 9   average_age            118 non-null    float64
 10  foreigners_number      118 non-null    int64
 11  foreigners_percentage  113 non-null    float64
 12  total_market_value     115 non-null    float64
 13  coach_name             0 non-null      float64
 14  fifa_ranking           118 non-null    int64
 15  last_season            118 non-null    int64
 16  url                    118 non-null    str
dtypes: float64(4), int64(6), str(7)
memory usage: 15.8 KB

In [30]:
national_teams.isnull().sum()

national_team_id           0
name                       0
team_code                  0
country_id                 0
country_name               0
country_code               0
confederation              1
team_image_url             0
squad_size                 0
average_age                0
foreigners_number          0
foreigners_percentage      5
total_market_value         3
coach_name               118
fifa_ranking               0
last_season                0
url                        0
dtype: int64

In [31]:
results_teams = set(results['home_team'].unique()) | set(results['away_team'].unique())
rankings_teams = set(fifa_rankings['country_full'].unique())

# Teams in results but not in rankings
print(results_teams - rankings_teams)

# Teams in rankings but not in results
print(rankings_teams - results_teams)

{'Frøya', 'Padania', 'Alderney', 'Åland Islands', 'West Papua', 'Mapuche', 'Saint Barthélemy', 'Gozo', 'Yorkshire', 'Felvidék', 'Greenland', 'Tibet', 'Catalonia', 'Guernsey', 'Western Isles', 'Hitra', 'Maule Sur', 'Arameans Suryoye', 'Réunion', 'Monaco', 'Hong Kong', 'Délvidék', 'South Korea', 'Găgăuzia', 'United States Virgin Islands', 'Saugeais', 'Cilento', 'Isle of Wight', 'Silesia', 'Parishes of Jersey', 'Brittany', 'Kurdistan', 'Marshall Islands', 'Martinique', 'Guadeloupe', 'Hmong', 'Mayotte', 'Panjab', 'Two Sicilies', 'Quebec', 'Yoruba Nation', 'Vietnam Republic', 'Aymara', 'Ellan Vannin', 'North Korea', 'South Yemen', 'Niue', 'Tamil Eelam', 'Barawa', 'Ambazonia', 'North Vietnam', 'Crimea', 'Western Armenia', 'Kárpátalja', 'Darfur', 'Shetland', 'Manchukuo', 'Kernow', 'Somaliland', 'Andalusia', 'Sealand', 'Rhodes', 'Occitania', 'Sark', 'Jersey', 'United Koreans in Japan', 'Artsakh', 'Székely Land', 'Micronesia', 'Saarland', 'Ivory Coast', 'Turkey', 'Zanzibar', 'Western Australia', 'Romani people', 'Northern Cyprus', 'Czech Republic', 'Saint Vincent and the Grenadines', 'Wallis Islands and Futuna', 'United States', 'Luhansk PR', 'Canary Islands', 'Abkhazia', 'Northern Mariana Islands', 'Ryūkyū', 'Republic of St. Pauli', 'Saint Helena', 'Ticino', 'Gotland', 'Elba Island', 'Franconia', 'French Guiana', 'Iraqi Kurdistan', 'Biafra', 'Palau', 'Chagos Islands', 'Western Sahara', 'Saint Martin', 'Kyrgyzstan', 'DR Congo', 'Vatican City', 'Saint Kitts and Nevis', 'Sápmi', 'Falkland Islands', 'County of Nice', 'Provence', 'Chechnya', 'South Ossetia', 'Tuvalu', 'Basque Country', 'Taiwan', 'Ynys Môn', 'Brunei', 'Asturias', 'Central Spain', 'Isle of Man', 'East Turkestan', 'German DR', 'Yemen DPR', 'Chameria', 'Menorca', 'Donetsk PR', 'Galicia', 'Madrid', 'Surrey', 'Orkney', 'Matabeleland', 'Kiribati', 'Gambia', 'Iran', 'Corsica', 'Cape Verde', 'Saare County', 'Saint Lucia', 'Cascadia', 'Bonaire', 'Saint Pierre and Miquelon', 'Sint Maarten', 'Raetia', 'Seborga', 'Kabylia'}
{'St Kitts and Nevis', 'Hong Kong, China', 'Serbia and Montenegro', 'Zaire', 'Netherlands Antilles', 'Kyrgyz Republic', 'Brunei Darussalam', 'The Gambia', 'Czechia', "Côte d'Ivoire", 'Korea DPR', 'Türkiye', 'Chinese Taipei', 'Congo DR', 'St Vincent and the Grenadines', 'US Virgin Islands', 'IR Iran', 'St Lucia', 'Korea Republic', 'Cabo Verde', 'USA'}

In [32]:
world_cup_teams = set(
    results[results['tournament'] == 'FIFA World Cup']['home_team'].unique()
) | set(
    results[results['tournament'] == 'FIFA World Cup']['away_team'].unique()
)

print(world_cup_teams)

{'Wales', 'Israel', 'Hungary', 'United Arab Emirates', 'Iraq', 'Colombia', 'Cuba', 'Haiti', 'Portugal', 'Netherlands', 'Egypt', 'South Korea', 'Uzbekistan', 'Denmark', 'Peru', 'Brazil', 'Republic of Ireland', 'Belgium', 'Honduras', 'Czechoslovakia', 'Spain', 'Serbia', 'Saudi Arabia', 'Jordan', 'Switzerland', 'Yugoslavia', 'Slovakia', 'North Korea', 'Panama', 'Indonesia', 'Togo', 'England', 'Nigeria', 'Tunisia', 'Austria', 'Canada', 'Iceland', 'Bolivia', 'Italy', 'Germany', 'Ivory Coast', 'Turkey', 'Jamaica', 'Bulgaria', 'China PR', 'Chile', 'New Zealand', 'Czech Republic', 'United States', 'Ukraine', 'Ecuador', 'Japan', 'Curaçao', 'Qatar', 'Argentina', 'Romania', 'France', 'Ghana', 'El Salvador', 'DR Congo', 'Slovenia', 'Bosnia and Herzegovina', 'Poland', 'Paraguay', 'Croatia', 'Norway', 'German DR', 'South Africa', 'Kuwait', 'Algeria', 'Cameroon', 'Trinidad and Tobago', 'Sweden', 'Senegal', 'Australia', 'Iran', 'Angola', 'Russia', 'Cape Verde', 'Greece', 'Uruguay', 'Scotland', 'Mexico', 'Costa Rica', 'Morocco', 'Northern Ireland'}

In [33]:
edge_cases = ['Republic of Ireland', 'China PR', 'Serbia', 'Bosnia and Herzegovina', 'Curaçao']

for team in edge_cases:
    in_rankings = team in set(fifa_rankings['country_full'].unique())
    print(f"{team}: {'✓ found' if in_rankings else '✗ not found'}")

Republic of Ireland: ✓ found
China PR: ✓ found
Serbia: ✓ found
Bosnia and Herzegovina: ✓ found
Curaçao: ✓ found

In [34]:
results

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49406,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49407,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49408,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49409,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49410,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [35]:
results.dtypes

date              str
home_team         str
away_team         str
home_score    float64
away_score    float64
tournament        str
city              str
country           str
neutral          bool
dtype: object

In [36]:
results['date'] = pd.to_datetime(results['date'])

In [39]:
results.dtypes

date          datetime64[us]
home_team                str
away_team                str
home_score           float64
away_score           float64
tournament               str
city                     str
country                  str
neutral                 bool
dtype: object

In [40]:
results.replace({
    'South Korea': 'Korea Republic',
    'North Korea': 'Korea DPR',
    'Ivory Coast': "Côte d'Ivoire",
    'Turkey': 'Türkiye',
    'Iran': 'IR Iran',
    'United States': 'USA',
    'DR Congo': 'Congo DR',
    'Czech Republic': 'Czechia',
    'Cape Verde': 'Cabo Verde'
}
)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49406,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,USA,True
49407,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,USA,True
49408,2026-06-27,Congo DR,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,USA,True
49409,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,USA,True
49410,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,USA,True

In [41]:
results

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49406,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49407,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49408,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49409,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49410,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [42]:
results = results.replace({
    'South Korea': 'Korea Republic',
    'North Korea': 'Korea DPR',
    'Ivory Coast': "Côte d'Ivoire",
    'Turkey': 'Türkiye',
    'Iran': 'IR Iran',
    'United States': 'USA',
    'DR Congo': 'Congo DR',
    'Czech Republic': 'Czechia',
    'Cape Verde': 'Cabo Verde'
}
)

In [43]:
# Check none of the old names remain
old_names = ['South Korea', 'Ivory Coast', 'Turkey', 'Iran', 'United States', 'DR Congo', 'Czech Republic', 'Cape Verde']

for name in old_names:
    found = (results['home_team'] == name).any() or (results['away_team'] == name).any()
    print(f"{name}: {'✗ still exists' if found else '✓ replaced'}")

South Korea: ✓ replaced
Ivory Coast: ✓ replaced
Turkey: ✓ replaced
Iran: ✓ replaced
United States: ✓ replaced
DR Congo: ✓ replaced
Czech Republic: ✓ replaced
Cape Verde: ✓ replaced

In [44]:
historical_results = results.notna()

In [45]:
historical_results

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
49406,True,True,True,False,False,True,True,True,True
49407,True,True,True,False,False,True,True,True,True
49408,True,True,True,False,False,True,True,True,True
49409,True,True,True,False,False,True,True,True,True
49410,True,True,True,False,False,True,True,True,True

In [49]:
historical_results = results[results['home_score'].notna()]

In [50]:
historical_results

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49334,2026-06-05,Russia,Burkina Faso,3.0,0.0,Friendly,Volgograd,Russia,False
49335,2026-06-05,Benin,Niger,1.0,1.0,Friendly,Casablanca,Morocco,True
49336,2026-06-05,Central African Republic,Togo,1.0,1.0,Friendly,Mohammedia,Morocco,True
49337,2026-06-05,Puerto Rico,Saudi Arabia,0.0,3.0,Friendly,Austin,USA,True
49338,2026-06-05,Vanuatu,Fiji,2.0,1.0,Friendly,Port Vila,Vanuatu,False

In [51]:
future_fixtures = results[results['home_score'].isnull()]

In [52]:
future_fixtures

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49339,2026-06-11,Mexico,South Africa,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49340,2026-06-11,Korea Republic,Czechia,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True
49341,2026-06-12,Canada,Bosnia and Herzegovina,NaN,NaN,FIFA World Cup,Toronto,Canada,False
49342,2026-06-12,USA,Paraguay,NaN,NaN,FIFA World Cup,Inglewood,USA,False
49343,2026-06-13,Qatar,Switzerland,NaN,NaN,FIFA World Cup,Santa Clara,USA,True
...,...,...,...,...,...,...,...,...,...
49406,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,USA,True
49407,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,USA,True
49408,2026-06-27,Congo DR,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,USA,True
49409,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,USA,True
49410,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,USA,True

In [53]:
print(historical_results.shape)
print(future_fixtures.shape)
print(historical_results.shape[0] + future_fixtures.shape[0])

(49339, 9)
(72, 9)
49411

In [55]:
historical_results['home_score'] = historical_results['home_score'].astype(int)

In [56]:
historical_results['away_score'] = historical_results['away_score'].astype(int)

In [57]:
historical_results[['home_score', 'away_score']].dtypes

home_score    int64
away_score    int64
dtype: object

In [60]:
import numpy as np

conditions = [
    historical_results['home_score'] > historical_results['away_score'],
    historical_results['home_score'] < historical_results['away_score'],
    historical_results['home_score'] == historical_results['away_score']
]

choices = [
    'Home Win',
    'Away Win',
    'Draw'
]

historical_results.loc[:, 'outcome'] = np.select(conditions, choices, default='Unknown')

In [61]:
historical_results['outcome'].value_counts()

outcome
Home Win    24177
Away Win    13943
Draw        11219
Name: count, dtype: int64

In [62]:
historical_results['tournament'].value_counts()

tournament
Friendly                                18333
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                            964
                                        ...
Copa Confraternidad                         1
Benedikt Fontana Cup                        1
ConIFA Challenger Cup                       1
CONIFA World Cup qualification              1
South Asian Super Cup                       1
Name: count, Length: 199, dtype: int64

In [63]:
print(historical_results['tournament'].unique())

<StringArray>
[                                         'Friendly',
                         'British Home Championship',
                              'Évence Coppée Trophy',
                                      'Muratti Vase',
                                       'Copa Lipton',
                                       'Copa Newton',
                       'Copa Premio Honor Argentino',
                                     'Olympic Games',
                        'Copa Premio Honor Uruguayo',
                    'Far Eastern Championship Games',
 ...
                   'EAFF Championship qualification',
                                     'Mapinduzi Cup',
                                   'Canadian Shield',
                           'Outrigger Challenge Cup',
                             'South Asian Super Cup',
                                   'CONCACAF Series',
                          'Al Ain International Cup',
              'Morocco, Capital of African Football',
                                  'Mukuru 4 Nations',
 'Diamond Jubilee International Football Tournament']
Length: 199, dtype: str

In [66]:
tournament_weights = {
    # Tier 4 - World Cup
    'FIFA World Cup': 4,
    
    # Tier 3 - Major tournaments
    'UEFA Euro': 3,
    'Copa América': 3,   
    'African Cup of Nations': 3,
    'AFC Asian Cup': 3,
    'Gold Cup': 3,

    
    # Tier 2 - Qualification
    'FIFA World Cup qualification': 2,
    'UEFA Euro qualification': 2,
    'African Cup of Nations qualification': 2,
    'AFC Asian Cup qualification': 2,
    'Gold Cup qualification': 2,
    
    # Tier 1 - Friendly
    'Friendly': 1,
    'Olympic Games': 1
}

historical_results.loc[:, 'tournament_weight'] = historical_results['tournament'].map(tournament_weights).fillna(1).astype(int)

In [67]:
historical_results['tournament_weight'].value_counts()

tournament_weight
1    30593
2    14839
3     2943
4      964
Name: count, dtype: int64

In [68]:
historical_results[historical_results['tournament'] == 'FIFA World Cup']['tournament_weight'].unique()

array([4])

In [69]:
historical_results.to_csv('../data/processed/historical_results.csv', index=False)
future_fixtures.to_csv('../data/processed/future_fixtures.csv', index=False)

In [70]:
fifa_rankings['rank_date'] = pd.to_datetime(fifa_rankings['rank_date'])

In [73]:
fifa_rankings = fifa_rankings.drop('Unnamed: 0', axis=1)

In [75]:
fifa_rankings = fifa_rankings[fifa_rankings['rank'].notna()]

In [76]:
fifa_rankings.shape

(70185, 8)

In [77]:
fifa_rankings.to_csv('../data/processed/fifa_rankings_clean.csv', index=False)

In [78]:
players = players[['player_id', 'name', 'country_of_citizenship', 'position', 'international_caps', 'market_value_in_eur']]

In [79]:
players = players[players['country_of_citizenship'].notna()]

In [80]:
players.shape

(47428, 6)

In [81]:
player_valuations = player_valuations.drop('player_club_domestic_competition_id', axis = 1)

In [82]:
player_valuations['date'] = pd.to_datetime(player_valuations['date'])

In [83]:
player_valuations.shape

(507815, 5)

In [84]:
player_valuations.to_csv('../data/processed/player_valuations_clean.csv', index=False)

In [85]:
national_teams = national_teams[['national_team_id', 'name', 'country_name', 'confederation']]

In [86]:
national_teams.shape

(118, 4)

In [87]:
national_teams.to_csv('../data/processed/national_teams_clean.csv', index=False)

In [88]:
players.to_csv('../data/processed/players_clean.csv', index=False)